language: ruby

# Apparently sudo is required to test on Rubinius and JRuby-head
sudo: required

# See https://docs.travis-ci.com/user/languages/ruby/#Rubinius
dist: trusty

rvm:
  # MRI
  - ruby-head
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - 1.9.2 # allowed to fail until Travis binary for this is fixed
  - 1.9.3
  - 1.8.7
  - ree
  # JRuby
  - jruby-head
  - jruby-9.1 # allowed to fail due to https://github.com/travis-ci/travis-ci/issues/9049
  - jruby-9.0
  - jruby-19mode
  - jruby-18mode
  # Rubinius
  - rubinius-3

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.2 # See build error https://travis-ci.org/tcrayford/Values/jobs/202728857
    - rvm: jruby-head
    - rvm: jruby-9.1 # See build error https://travis-ci.org/ms-ati/docile/jobs/327830706
    - rvm: rubinius-3
  fast_finish: true
